{% set name = "cppzmq" %}
{% set version = "4.2.3" %}
{% set sha256 = "3e6b57bf49115f4ae893b1ff7848ead7267013087dc7be1ab27636a97144d373" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zeromq/cppzmq/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
build:
    noarch: ''
    noarch_python: false
    number: '0'
    string: 'cling_0'
    skip: true  # [win and py<35]
    features:
        - cling
        - vc14    # [win]

requirements:
    build:
        - cling-patches
        - cmake
        - toolchain
        - zeromq 4.2.3
        - gcc-7                       # [linux and not armv7l]
    run:
        - cling-patches
        - zeromq 4.2.3
        - vs2015_runtime              # [win]
        - libgcc-7                    # [linux and not armv7l]
test:
    commands:
        - if exist %LIBRARY_PREFIX%\share\cmake\cppzmq\cppzmqConfig.cmake (exit 0) else (exit 1)        # [win]
        - if exist %LIBRARY_PREFIX%\share\cmake\cppzmq\cppzmqConfigVersion.cmake (exit 0) else (exit 1) # [win]
        - test -f $PREFIX/share/cmake/cppzmq/cppzmqConfig.cmake                                         # [unix]
        - test -f $PREFIX/share/cmake/cppzmq/cppzmqConfigVersion.cmake                                  # [unix]
about:
    home: http://zeromq.org
    license: MIT
    summary: C++ bindings for 0MQ
extra:
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - JohanMabille
        - gouarin
