package:
    name: cppzmq
    version: 4.2.2
source:
    fn: cppzmq-4.2.2.tar.gz
    sha256: 3ef50070ac5877c06c6bb25091028465020e181bbfd08f110294ed6bc419737d
    url: https://github.com/zeromq/cppzmq/archive/v4.2.2.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    string: 'cling_0'
    skip: true  # [win and py<35]
    features:
        - cling
        - vc14    # [win]

requirements:
    build:
        - cling-patches
        - cmake
        - toolchain
        - zeromq 4.2.2
        - gcc-7                       # [linux and not armv7l]
    run:
        - cling-patches
        - zeromq 4.2.2
        - vs2015_runtime              # [win]
        - libgcc-7                    # [linux and not armv7l]
test:
    commands:
        - if exist %LIBRARY_PREFIX%\share\cmake\cppzmq\cppzmqConfig.cmake (exit 0) else (exit 1)        # [win]
        - if exist %LIBRARY_PREFIX%\share\cmake\cppzmq\cppzmqConfigVersion.cmake (exit 0) else (exit 1) # [win]
        - test -f $PREFIX/share/cmake/cppzmq/cppzmqConfig.cmake                                         # [unix]
        - test -f $PREFIX/share/cmake/cppzmq/cppzmqConfigVersion.cmake                                  # [unix]
about:
    home: http://zeromq.org
    license: MIT
    summary: C++ bindings for 0MQ
extra:
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - JohanMabille
        - gouarin
